/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_guillermoespinal;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author admin
 */
public class Frame_principal extends javax.swing.JFrame {

    /**
     * Creates new form Frame_principal
     */
    public Frame_principal() {
        initComponents();
        //acordate de borrar esto
        yo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_pass = new javax.swing.JPasswordField();
        tf_usuario = new javax.swing.JTextField();
        bt_login = new javax.swing.JButton();
        jd_crearusuario = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_crearusuario = new javax.swing.JTextField();
        tf_crearapellido = new javax.swing.JTextField();
        tf_crearnombre = new javax.swing.JTextField();
        tf_crearcontra = new javax.swing.JTextField();
        jd_fecha = new com.toedter.calendar.JDateChooser();
        bt_color = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        crearyagregar = new javax.swing.JDialog();
        cb_mazos = new javax.swing.JComboBox<>();
        cb_carta = new javax.swing.JComboBox<>();
        bt_agregarcarta = new javax.swing.JButton();
        tf_ptvida = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_dano = new javax.swing.JTextField();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jDialog4 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtree_mazos1 = new javax.swing.JTree();
        bt_crearyagregar1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mn_login = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jLabel1.setText("LOGIN");

        jLabel2.setText("Usuario: ");

        jLabel3.setText("Contrasena:");

        bt_login.setText("Login");
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bt_login)
                    .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_loginLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_loginLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(70, 70, 70)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(bt_login)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jLabel4.setText("Usuario: ");

        jLabel5.setText("Apellido: ");

        jLabel6.setText("Color favorito: ");

        jLabel7.setText("Crear Usuario");

        jLabel8.setText("Fecha: ");

        jLabel9.setText("Nombre; ");

        jLabel10.setText("Contra: ");

        bt_color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_colorMouseClicked(evt);
            }
        });

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearusuarioLayout = new javax.swing.GroupLayout(jd_crearusuario.getContentPane());
        jd_crearusuario.getContentPane().setLayout(jd_crearusuarioLayout);
        jd_crearusuarioLayout.setHorizontalGroup(
            jd_crearusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jd_crearusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_crearnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGroup(jd_crearusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel7))
                            .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_crearapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                        .addGroup(jd_crearusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_crearusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel10))
                            .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_crearusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1)
                            .addComponent(tf_crearcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jd_crearusuarioLayout.setVerticalGroup(
            jd_crearusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_crearusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_crearusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tf_crearcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_crearusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_crearapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jd_crearusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf_crearnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jd_crearusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jd_crearusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jd_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99))
                    .addGroup(jd_crearusuarioLayout.createSequentialGroup()
                        .addComponent(bt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        cb_mazos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mazo1", "Mazo2", "Mazo3" }));
        cb_mazos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_mazosItemStateChanged(evt);
            }
        });

        cb_carta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minipekka ", "Montapuerco", "Golem", "Lenador", "Dragon Infernal ", "Dragon", "Gigante Noble", "Pandilla de Duendes" }));

        bt_agregarcarta.setText("Agregar");
        bt_agregarcarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_agregarcartaMouseClicked(evt);
            }
        });

        jLabel11.setText("Puntos de vida:");

        jLabel13.setText("Dano:");

        javax.swing.GroupLayout crearyagregarLayout = new javax.swing.GroupLayout(crearyagregar.getContentPane());
        crearyagregar.getContentPane().setLayout(crearyagregarLayout);
        crearyagregarLayout.setHorizontalGroup(
            crearyagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearyagregarLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(cb_mazos, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_carta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearyagregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_agregarcarta)
                .addGap(237, 237, 237))
            .addGroup(crearyagregarLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_ptvida, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_dano, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        crearyagregarLayout.setVerticalGroup(
            crearyagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearyagregarLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(crearyagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_mazos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_carta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(crearyagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearyagregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_ptvida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_dano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(bt_agregarcarta)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mazos");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mazo3");
        treeNode1.add(treeNode2);
        jtree_mazos1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jtree_mazos1);

        bt_crearyagregar1.setText("crear y agregar carta a mazo");
        bt_crearyagregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearyagregar1MouseClicked(evt);
            }
        });
        bt_crearyagregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_crearyagregar1ActionPerformed(evt);
            }
        });

        jMenu3.setText("Login");

        mn_login.setText("Login");
        mn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_loginMouseClicked(evt);
            }
        });
        mn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_loginActionPerformed(evt);
            }
        });
        jMenu3.add(mn_login);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addComponent(bt_crearyagregar1)
                .addGap(58, 58, 58)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_crearyagregar1)
                        .addGap(45, 45, 45))))
        );

        pack();
    }// </editor-fold>                        

    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {                                      
       String user = tf_usuario.getText();
       String pass = tf_pass.getText();
       boolean exist=false;
        for (Usuario usuario : usuarios) {
            if (user.equals(usuario.getUsuario())&&user.equals(usuario.getContra())){
                user_global.setUsuario(user);
                exist =true;
                
            }
        }
        if (!exist) {
            //abrir_login();
            abrir_creacionuser();
           
            
        }
      
       
    }                                     

     private void abrir_login(){
        jd_login.setModal(true);//este es para bloquear los anteriores
        jd_login.pack();//acopla el tamano de la ventana
        jd_login.setLocationRelativeTo(this);
        jd_login.setVisible(true);
        
    }
     private void abrir_creacionuser(){
        jd_crearusuario.setModal(true);//este es para bloquear los anteriores
        jd_crearusuario.pack();//acopla el tamano de la ventana
        jd_crearusuario.setLocationRelativeTo(this);
        jd_crearusuario.setVisible(true);
        
    }
     /*private void abrir_inicio(){
        jd_inicio.setModal(true);//este es para bloquear los anteriores
        jd_inicio.pack();//acopla el tamano de la ventana
        jd_inicio.setLocationRelativeTo(this);
        jd_inicio.setVisible(true);
        
    }*/
     private void abrir_crear(){
        crearyagregar.setModal(true);//este es para bloquear los anteriores
        crearyagregar.pack();//acopla el tamano de la ventana
        crearyagregar.setLocationRelativeTo(this);
        crearyagregar.setVisible(true);
        
    }
    
    
    private void bt_colorMouseClicked(java.awt.event.MouseEvent evt) {                                      
   
        bt_color.setBackground(JColorChooser.showDialog(this,"Seleccione un color",Color.yellow));
    }                                     

    private void mn_loginMouseClicked(java.awt.event.MouseEvent evt) {                                      
       abrir_login();
    }                                     

    private void mn_loginActionPerformed(java.awt.event.ActionEvent evt) {                                         
        abrir_login();
    }                                        

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {                                      
         String nombre=tf_crearnombre.getText();
            String usuario=tf_crearusuario.getText();
            String contra=tf_crearcontra.getText();
            Color color = bt_color.getBackground();
            Date fecha =jd_fecha.getDate();
            //sacar la edad de el user 
            long dife = new Date().getTime()-fecha.getTime();
            int anos = (int)((dife/(1000*60*60*24))/365);
            //System.out.println(anos);
            
            Usuario newuser = new Usuario(nombre, usuario, usuario, contra, fecha, anos);
            usuarios.add(newuser);
            user_global=newuser;
            //(new Date()).getTime()-((s.getFecha_nacimiento().getTime())/(1000*60*60*24))
    }                                     

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
      //abrir_inicio();
    
      user_mazo1=user_global.getMazo1();
      user_mazo2=user_global.getMazo2();
      user_mazo3=user_global.getMazo3();
     /* DefaultTreeModel modeloArbol = (DefaultTreeModel) this.jtree_mazos.getModel();
      DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
      DefaultMutableTreeNode mazo1 = new DefaultMutableTreeNode(user_mazo1);
      DefaultMutableTreeNode mazo2 = new DefaultMutableTreeNode(user_mazo2);
      DefaultMutableTreeNode mazo3 = new DefaultMutableTreeNode(user_mazo3);
      raiz.add(mazo1);
      raiz.add(mazo2);
      raiz.add(mazo3);
      modeloArbol.reload();*/
    

      
      
    }                                      

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {                                    
        //abrir_inicio();
    }                                   

    private void bt_crearyagregar1MouseClicked(java.awt.event.MouseEvent evt) {                                               
        abrir_crear();
    }                                              

    private void bt_crearyagregar1ActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void cb_mazosItemStateChanged(java.awt.event.ItemEvent evt) {                                          
        
    }                                         

    private void bt_agregarcartaMouseClicked(java.awt.event.MouseEvent evt) {                                             
        try {
            int dano = Integer.parseInt(tf_dano.getText());
            int ptvida = Integer.parseInt(tf_ptvida.getText());
            //int dano = Integer.parseInt(tf_dano.getText());
            Cartas newcarta= new Cartas();
            switch (cb_carta.getSelectedIndex()){
            case 0:
                newcarta = new Minipekka(dano, ptvida);
                break;
            case 1:
                newcarta = new Montapuerco(dano, ptvida);
                break;
            case 2:
                 newcarta = new Golem(dano, ptvida);
                break;
            case 3:
                newcarta = new Leñador(dano, ptvida);
                break;
            case 4:
                 newcarta = new Dragon_Infernal(dano, ptvida);
                break;
            case 5:
                 newcarta = new Dragon(dano, ptvida);
                break;
            case 6:
                 newcarta = new Gigante_noble(dano, ptvida);
                break;
            case 7:
                 newcarta = new Pandilla_duendes(dano, ptvida);
                break;
        }
            switch (cb_mazos.getSelectedIndex()){
            case 0:
                if ((user_global.getMazo1().getCartas().size())>3) {
                    JOptionPane.showMessageDialog(this, "Este mazo ya tiene suficientes cartas");
                }else {
                    user_global.getMazo1().setCarta(newcarta);
                     DefaultTreeModel modeloarbol = (DefaultTreeModel)jtree_mazos1.getModel();
                     DefaultMutableTreeNode raiz =(DefaultMutableTreeNode)modeloarbol.getRoot();
                     DefaultMutableTreeNode hijo1= (DefaultMutableTreeNode)raiz.getChildAt(0);
                     DefaultMutableTreeNode hijo2= (DefaultMutableTreeNode)raiz.getChildAt(1);
                     DefaultMutableTreeNode hijo3= (DefaultMutableTreeNode)raiz.getChildAt(2);
                     DefaultMutableTreeNode hijito = new DefaultMutableTreeNode(newcarta);
                     hijo1.add(hijito);
                     raiz.add(hijo1);
                     raiz.add(hijo2);
                     raiz.add(hijo3);
                     modeloarbol.reload();
                  /* raiz.add(hijo1);
                   add(hijo)
                           
                           model.setRoot(nuevaRaiz)*/
                }
                break;
            case 1:
                 if ((user_global.getMazo2().getCartas().size())>3) {
                    JOptionPane.showMessageDialog(this, "Este mazo ya tiene suficientes cartas");
                }else {
                    user_global.getMazo2().setCarta(newcarta);
                     DefaultTreeModel modeloarbol = (DefaultTreeModel)jtree_mazos1.getModel();
                     DefaultMutableTreeNode raiz =(DefaultMutableTreeNode)modeloarbol.getRoot();
                     DefaultMutableTreeNode hijo1= (DefaultMutableTreeNode)raiz.getChildAt(0);
                     DefaultMutableTreeNode hijo2= (DefaultMutableTreeNode)raiz.getChildAt(1);
                     DefaultMutableTreeNode hijo3= (DefaultMutableTreeNode)raiz.getChildAt(2);
                     DefaultMutableTreeNode hijito = new DefaultMutableTreeNode(newcarta);
                     hijo2.add(hijito);
                     raiz.add(hijo1);
                     raiz.add(hijo2);
                     raiz.add(hijo3);
                     modeloarbol.reload();
                     
                }
                  //user_global.getMazo2().setCarta(newcarta);
                break;
            case 2:
                 if ((user_global.getMazo3().getCartas().size())>3) {
                    JOptionPane.showMessageDialog(this, "Este mazo ya tiene suficientes cartas");
                }else {
                    user_global.getMazo3().setCarta(newcarta);
                    DefaultTreeModel modeloarbol = (DefaultTreeModel)jtree_mazos1.getModel();
                     DefaultMutableTreeNode raiz =(DefaultMutableTreeNode)modeloarbol.getRoot();
                     DefaultMutableTreeNode hijo1= (DefaultMutableTreeNode)raiz.getChildAt(0);
                     DefaultMutableTreeNode hijo2= (DefaultMutableTreeNode)raiz.getChildAt(1);
                     DefaultMutableTreeNode hijo3= (DefaultMutableTreeNode)raiz.getChildAt(2);
                     DefaultMutableTreeNode hijito = new DefaultMutableTreeNode(newcarta);
                     hijo3.add(hijito);
                     raiz.add(hijo1);
                     raiz.add(hijo2);
                     raiz.add(hijo3);
                     modeloarbol.reload();
                }
                break;
        }
            
        } catch (Exception e) {
        }
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_principal().setVisible(true);
            }
        });
    }
    public void yo(){
        user_global=yo;
        //user_global.setMazo1(user_mazo1);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_agregarcarta;
    private javax.swing.JButton bt_color;
    private javax.swing.JButton bt_crearyagregar1;
    private javax.swing.JButton bt_login;
    private javax.swing.JComboBox<String> cb_carta;
    private javax.swing.JComboBox<String> cb_mazos;
    private javax.swing.JDialog crearyagregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_crearusuario;
    private com.toedter.calendar.JDateChooser jd_fecha;
    private javax.swing.JDialog jd_login;
    private javax.swing.JTree jtree_mazos1;
    private javax.swing.JMenuItem mn_login;
    private javax.swing.JTextField tf_crearapellido;
    private javax.swing.JTextField tf_crearcontra;
    private javax.swing.JTextField tf_crearnombre;
    private javax.swing.JTextField tf_crearusuario;
    private javax.swing.JTextField tf_dano;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JTextField tf_ptvida;
    private javax.swing.JTextField tf_usuario;
    // End of variables declaration                   
ArrayList<Usuario> usuarios = new ArrayList();
Usuario user_global;
Mazo user_mazo1;
Mazo user_mazo2;
Mazo user_mazo3;
Usuario yo= new Usuario();

//acordate de borrar esto


}
